CREATE TABLE nationalities (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nationality VARCHAR(100),
    country_code CHAR(2)
);

INSERT INTO nationalities (nationality, country_code) VALUES ('Afghan', 'AF');
INSERT INTO nationalities (nationality, country_code) VALUES ('Albanian', 'AL');
INSERT INTO nationalities (nationality, country_code) VALUES ('Algerian', 'DZ');
INSERT INTO nationalities (nationality, country_code) VALUES ('American', 'US');
INSERT INTO nationalities (nationality, country_code) VALUES ('Andorran', 'AD');
INSERT INTO nationalities (nationality, country_code) VALUES ('Angolan', 'AO');
INSERT INTO nationalities (nationality, country_code) VALUES ('Antiguan and Barbudan', 'AG');
INSERT INTO nationalities (nationality, country_code) VALUES ('Argentine', 'AR');
INSERT INTO nationalities (nationality, country_code) VALUES ('Armenian', 'AM');
INSERT INTO nationalities (nationality, country_code) VALUES ('Australian', 'AU');
INSERT INTO nationalities (nationality, country_code) VALUES ('Austrian', 'AT');
INSERT INTO nationalities (nationality, country_code) VALUES ('Azerbaijani', 'AZ');
INSERT INTO nationalities (nationality, country_code) VALUES ('Bahamian', 'BS');
INSERT INTO nationalities (nationality, country_code) VALUES ('Bahraini', 'BH');
INSERT INTO nationalities (nationality, country_code) VALUES ('Bangladeshi', 'BD');
INSERT INTO nationalities (nationality, country_code) VALUES ('Barbadian', 'BB');
INSERT INTO nationalities (nationality, country_code) VALUES ('Belarusian', 'BY');
INSERT INTO nationalities (nationality, country_code) VALUES ('Belgian', 'BE');
INSERT INTO nationalities (nationality, country_code) VALUES ('Belizean', 'BZ');
INSERT INTO nationalities (nationality, country_code) VALUES ('Beninese', 'BJ');
INSERT INTO nationalities (nationality, country_code) VALUES ('Bhutanese', 'BT');
INSERT INTO nationalities (nationality, country_code) VALUES ('Bolivian', 'BO');
INSERT INTO nationalities (nationality, country_code) VALUES ('Bosnian', 'BA');
INSERT INTO nationalities (nationality, country_code) VALUES ('Botswanan', 'BW');
INSERT INTO nationalities (nationality, country_code) VALUES ('Brazilian', 'BR');
INSERT INTO nationalities (nationality, country_code) VALUES ('British', 'GB');
INSERT INTO nationalities (nationality, country_code) VALUES ('Bruneian', 'BN');
INSERT INTO nationalities (nationality, country_code) VALUES ('Bulgarian', 'BG');
INSERT INTO nationalities (nationality, country_code) VALUES ('Burkinabé', 'BF');
INSERT INTO nationalities (nationality, country_code) VALUES ('Burmese', 'MM');
INSERT INTO nationalities (nationality, country_code) VALUES ('Burundian', 'BI');
INSERT INTO nationalities (nationality, country_code) VALUES ('Cabo Verdean', 'CV');
INSERT INTO nationalities (nationality, country_code) VALUES ('Cambodian', 'KH');
INSERT INTO nationalities (nationality, country_code) VALUES ('Cameroonian', 'CM');
INSERT INTO nationalities (nationality, country_code) VALUES ('Canadian', 'CA');
INSERT INTO nationalities (nationality, country_code) VALUES ('Central African', 'CF');
INSERT INTO nationalities (nationality, country_code) VALUES ('Chadian', 'TD');
INSERT INTO nationalities (nationality, country_code) VALUES ('Chilean', 'CL');
INSERT INTO nationalities (nationality, country_code) VALUES ('Chinese', 'CN');
INSERT INTO nationalities (nationality, country_code) VALUES ('Colombian', 'CO');
INSERT INTO nationalities (nationality, country_code) VALUES ('Comoran', 'KM');
INSERT INTO nationalities (nationality, country_code) VALUES ('Congolese (Congo-Brazzaville)', 'CG');
INSERT INTO nationalities (nationality, country_code) VALUES ('Congolese (Congo-Kinshasa)', 'CD');
INSERT INTO nationalities (nationality, country_code) VALUES ('Costa Rican', 'CR');
INSERT INTO nationalities (nationality, country_code) VALUES ('Croatian', 'HR');
INSERT INTO nationalities (nationality, country_code) VALUES ('Cuban', 'CU');
INSERT INTO nationalities (nationality, country_code) VALUES ('Cypriot', 'CY');
INSERT INTO nationalities (nationality, country_code) VALUES ('Czech', 'CZ');
INSERT INTO nationalities (nationality, country_code) VALUES ('Danish', 'DK');
INSERT INTO nationalities (nationality, country_code) VALUES ('Djiboutian', 'DJ');
INSERT INTO nationalities (nationality, country_code) VALUES ('Dominican', 'DO');
INSERT INTO nationalities (nationality, country_code) VALUES ('Dutch', 'NL');
INSERT INTO nationalities (nationality, country_code) VALUES ('East Timorese', 'TL');
INSERT INTO nationalities (nationality, country_code) VALUES ('Ecuadorean', 'EC');
INSERT INTO nationalities (nationality, country_code) VALUES ('Egyptian', 'EG');
INSERT INTO nationalities (nationality, country_code) VALUES ('Salvadoran', 'SV');
INSERT INTO nationalities (nationality, country_code) VALUES ('Equatorial Guinean', 'GQ');
INSERT INTO nationalities (nationality, country_code) VALUES ('Eritrean', 'ER');
INSERT INTO nationalities (nationality, country_code) VALUES ('Estonian', 'EE');
INSERT INTO nationalities (nationality, country_code) VALUES ('Eswatini', 'SZ');
INSERT INTO nationalities (nationality, country_code) VALUES ('Ethiopian', 'ET');
INSERT INTO nationalities (nationality, country_code) VALUES ('Fijian', 'FJ');
INSERT INTO nationalities (nationality, country_code) VALUES ('Finnish', 'FI');
INSERT INTO nationalities (nationality, country_code) VALUES ('French', 'FR');
INSERT INTO nationalities (nationality, country_code) VALUES ('Gabonese', 'GA');
INSERT INTO nationalities (nationality, country_code) VALUES ('Gambian', 'GM');
INSERT INTO nationalities (nationality, country_code) VALUES ('Georgian', 'GE');
INSERT INTO nationalities (nationality, country_code) VALUES ('German', 'DE');
INSERT INTO nationalities (nationality, country_code) VALUES ('Ghanaian', 'GH');
INSERT INTO nationalities (nationality, country_code) VALUES ('Greek', 'GR');
INSERT INTO nationalities (nationality, country_code) VALUES ('Grenadian', 'GD');
INSERT INTO nationalities (nationality, country_code) VALUES ('Guatemalan', 'GT');
INSERT INTO nationalities (nationality, country_code) VALUES ('Guinean', 'GN');
INSERT INTO nationalities (nationality, country_code) VALUES ('Bissau-Guinean', 'GW');
INSERT INTO nationalities (nationality, country_code) VALUES ('Guyanese', 'GY');
INSERT INTO nationalities (nationality, country_code) VALUES ('Haitian', 'HT');
INSERT INTO nationalities (nationality, country_code) VALUES ('Honduran', 'HN');
INSERT INTO nationalities (nationality, country_code) VALUES ('Hungarian', 'HU');
INSERT INTO nationalities (nationality, country_code) VALUES ('Icelandic', 'IS');
INSERT INTO nationalities (nationality, country_code) VALUES ('Indian', 'IN');
INSERT INTO nationalities (nationality, country_code) VALUES ('Indonesian', 'ID');
INSERT INTO nationalities (nationality, country_code) VALUES ('Iranian', 'IR');
INSERT INTO nationalities (nationality, country_code) VALUES ('Iraqi', 'IQ');
INSERT INTO nationalities (nationality, country_code) VALUES ('Irish', 'IE');
INSERT INTO nationalities (nationality, country_code) VALUES ('Israeli', 'IL');
INSERT INTO nationalities (nationality, country_code) VALUES ('Italian', 'IT');
INSERT INTO nationalities (nationality, country_code) VALUES ('Ivorian', 'CI');
INSERT INTO nationalities (nationality, country_code) VALUES ('Jamaican', 'JM');
INSERT INTO nationalities (nationality, country_code) VALUES ('Japanese', 'JP');
INSERT INTO nationalities (nationality, country_code) VALUES ('Jordanian', 'JO');
INSERT INTO nationalities (nationality, country_code) VALUES ('Kazakh', 'KZ');
INSERT INTO nationalities (nationality, country_code) VALUES ('Kenyan', 'KE');
INSERT INTO nationalities (nationality, country_code) VALUES ('Kiribati', 'KI');
INSERT INTO nationalities (nationality, country_code) VALUES ('Kuwaiti', 'KW');
INSERT INTO nationalities (nationality, country_code) VALUES ('Kyrgyz', 'KG');
INSERT INTO nationalities (nationality, country_code) VALUES ('Lao', 'LA');
INSERT INTO nationalities (nationality, country_code) VALUES ('Latvian', 'LV');
INSERT INTO nationalities (nationality, country_code) VALUES ('Lebanese', 'LB');
INSERT INTO nationalities (nationality, country_code) VALUES ('Liberian', 'LR');
INSERT INTO nationalities (nationality, country_code) VALUES ('Libyan', 'LY');
INSERT INTO nationalities (nationality, country_code) VALUES ('Liechtensteiner', 'LI');
INSERT INTO nationalities (nationality, country_code) VALUES ('Lithuanian', 'LT');
INSERT INTO nationalities (nationality, country_code) VALUES ('Luxembourgish', 'LU');
INSERT INTO nationalities (nationality, country_code) VALUES ('Malagasy', 'MG');
INSERT INTO nationalities (nationality, country_code) VALUES ('Malawian', 'MW');
INSERT INTO nationalities (nationality, country_code) VALUES ('Malaysian', 'MY');
INSERT INTO nationalities (nationality, country_code) VALUES ('Maldivian', 'MV');
INSERT INTO nationalities (nationality, country_code) VALUES ('Malian', 'ML');
INSERT INTO nationalities (nationality, country_code) VALUES ('Maltese', 'MT');
INSERT INTO nationalities (nationality, country_code) VALUES ('Marshallese', 'MH');
INSERT INTO nationalities (nationality, country_code) VALUES ('Mauritanian', 'MR');
INSERT INTO nationalities (nationality, country_code) VALUES ('Mauritian', 'MU');
INSERT INTO nationalities (nationality, country_code) VALUES ('Mexican', 'MX');
INSERT INTO nationalities (nationality, country_code) VALUES ('Micronesian', 'FM');
INSERT INTO nationalities (nationality, country_code) VALUES ('Moldovan', 'MD');
INSERT INTO nationalities (nationality, country_code) VALUES ('Monégasque', 'MC');
INSERT INTO nationalities (nationality, country_code) VALUES ('Mongolian', 'MN');
INSERT INTO nationalities (nationality, country_code) VALUES ('Montenegrin', 'ME');
INSERT INTO nationalities (nationality, country_code) VALUES ('Moroccan', 'MA');
INSERT INTO nationalities (nationality, country_code) VALUES ('Mozambican', 'MZ');
INSERT INTO nationalities (nationality, country_code) VALUES ('Namibian', 'NA');
INSERT INTO nationalities (nationality, country_code) VALUES ('Nauruan', 'NR');
INSERT INTO nationalities (nationality, country_code) VALUES ('Nepalese', 'NP');
INSERT INTO nationalities (nationality, country_code) VALUES ('New Zealander', 'NZ');
INSERT INTO nationalities (nationality, country_code) VALUES ('Nicaraguan', 'NI');
INSERT INTO nationalities (nationality, country_code) VALUES ('Nigerien', 'NE');
INSERT INTO nationalities (nationality, country_code) VALUES ('Nigerian', 'NG');
INSERT INTO nationalities (nationality, country_code) VALUES ('North Korean', 'KP');
INSERT INTO nationalities (nationality, country_code) VALUES ('North Macedonian', 'MK');
INSERT INTO nationalities (nationality, country_code) VALUES ('Norwegian', 'NO');
INSERT INTO nationalities (nationality, country_code) VALUES ('Omani', 'OM');
INSERT INTO nationalities (nationality, country_code) VALUES ('Pakistani', 'PK');
INSERT INTO nationalities (nationality, country_code) VALUES ('Palauan', 'PW');
INSERT INTO nationalities (nationality, country_code) VALUES ('Palestinian', 'PS');
INSERT INTO nationalities (nationality, country_code) VALUES ('Panamanian', 'PA');
INSERT INTO nationalities (nationality, country_code) VALUES ('Papua New Guinean', 'PG');
INSERT INTO nationalities (nationality, country_code) VALUES ('Paraguayan', 'PY');
INSERT INTO nationalities (nationality, country_code) VALUES ('Peruvian', 'PE');
INSERT INTO nationalities (nationality, country_code) VALUES ('Philippine', 'PH');
INSERT INTO nationalities (nationality, country_code) VALUES ('Polish', 'PL');
INSERT INTO nationalities (nationality, country_code) VALUES ('Portuguese', 'PT');
INSERT INTO nationalities (nationality, country_code) VALUES ('Qatari', 'QA');
INSERT INTO nationalities (nationality, country_code) VALUES ('Romanian', 'RO');
INSERT INTO nationalities (nationality, country_code) VALUES ('Russian', 'RU');
INSERT INTO nationalities (nationality, country_code) VALUES ('Rwandan', 'RW');
INSERT INTO nationalities (nationality, country_code) VALUES ('Kittitian and Nevisian', 'KN');
INSERT INTO nationalities (nationality, country_code) VALUES ('Saint Lucian', 'LC');
INSERT INTO nationalities (nationality, country_code) VALUES ('Saint Vincentian', 'VC');
INSERT INTO nationalities (nationality, country_code) VALUES ('Samoan', 'WS');
INSERT INTO nationalities (nationality, country_code) VALUES ('San Marinese', 'SM');
INSERT INTO nationalities (nationality, country_code) VALUES ('Sao Tomean', 'ST');
INSERT INTO nationalities (nationality, country_code) VALUES ('Saudi', 'SA');
INSERT INTO nationalities (nationality, country_code) VALUES ('Senegalese', 'SN');
INSERT INTO nationalities (nationality, country_code) VALUES ('Serbian', 'RS');
INSERT INTO nationalities (nationality, country_code) VALUES ('Seychellois', 'SC');
INSERT INTO nationalities (nationality, country_code) VALUES ('Sierra Leonean', 'SL');
INSERT INTO nationalities (nationality, country_code) VALUES ('Singaporean', 'SG');
INSERT INTO nationalities (nationality, country_code) VALUES ('Slovak', 'SK');
INSERT INTO nationalities (nationality, country_code) VALUES ('Slovenian', 'SI');
INSERT INTO nationalities (nationality, country_code) VALUES ('Solomon Islander', 'SB');
INSERT INTO nationalities (nationality, country_code) VALUES ('Somali', 'SO');
INSERT INTO nationalities (nationality, country_code) VALUES ('South African', 'ZA');
INSERT INTO nationalities (nationality, country_code) VALUES ('South Korean', 'KR');
INSERT INTO nationalities (nationality, country_code) VALUES ('South Sudanese', 'SS');
INSERT INTO nationalities (nationality, country_code) VALUES ('Spanish', 'ES');
INSERT INTO nationalities (nationality, country_code) VALUES ('Sri Lankan', 'LK');
INSERT INTO nationalities (nationality, country_code) VALUES ('Sudanese', 'SD');
INSERT INTO nationalities (nationality, country_code) VALUES ('Surinamese', 'SR');
INSERT INTO nationalities (nationality, country_code) VALUES ('Swedish', 'SE');
INSERT INTO nationalities (nationality, country_code) VALUES ('Swiss', 'CH');
INSERT INTO nationalities (nationality, country_code) VALUES ('Syrian', 'SY');
INSERT INTO nationalities (nationality, country_code) VALUES ('Taiwanese', 'TW');
INSERT INTO nationalities (nationality, country_code) VALUES ('Tajik', 'TJ');
INSERT INTO nationalities (nationality, country_code) VALUES ('Tanzanian', 'TZ');
INSERT INTO nationalities (nationality, country_code) VALUES ('Thai', 'TH');
INSERT INTO nationalities (nationality, country_code) VALUES ('Togolese', 'TG');
INSERT INTO nationalities (nationality, country_code) VALUES ('Tongan', 'TO');
INSERT INTO nationalities (nationality, country_code) VALUES ('Trinidadian and Tobagonian', 'TT');
INSERT INTO nationalities (nationality, country_code) VALUES ('Tunisian', 'TN');
INSERT INTO nationalities (nationality, country_code) VALUES ('Turkish', 'TR');
INSERT INTO nationalities (nationality, country_code) VALUES ('Turkmen', 'TM');
INSERT INTO nationalities (nationality, country_code) VALUES ('Tuvaluan', 'TV');
INSERT INTO nationalities (nationality, country_code) VALUES ('Ugandan', 'UG');
INSERT INTO nationalities (nationality, country_code) VALUES ('Ukrainian', 'UA');
INSERT INTO nationalities (nationality, country_code) VALUES ('Emirati', 'AE');
INSERT INTO nationalities (nationality, country_code) VALUES ('Uruguayan', 'UY');
INSERT INTO nationalities (nationality, country_code) VALUES ('Uzbek', 'UZ');
INSERT INTO nationalities (nationality, country_code) VALUES ('Vanuatuan', 'VU');
INSERT INTO nationalities (nationality, country_code) VALUES ('Vatican', 'VA');
INSERT INTO nationalities (nationality, country_code) VALUES ('Venezuelan', 'VE');
INSERT INTO nationalities (nationality, country_code) VALUES ('Vietnamese', 'VN');
INSERT INTO nationalities (nationality, country_code) VALUES ('Yemeni', 'YE');
INSERT INTO nationalities (nationality, country_code) VALUES ('Zambian', 'ZM');
INSERT INTO nationalities (nationality, country_code) VALUES ('Zimbabwean', 'ZW');
