insert into r6_team (team_name, coach, nationality, ranking) values ('Team BDS', 'Elemzje', 'France', 1);
insert into r6_team (team_name, coach, nationality, ranking) values ('G2 Esports', 'Shas', 'Germany', 2);
insert into r6_team (team_name, coach, nationality, ranking) values ('Wolves Esports', 'Spark', 'Europe', 3);
insert into r6_team (team_name, coach, nationality, ranking) values ('Virtus.pro', 'Krasno', 'Russia', 4);
insert into r6_team (team_name, coach, nationality, ranking) values ('KOI', 'Txmpe', 'Spain', 5);
insert into r6_team (team_name, coach, nationality, ranking) values ('MNM Gaming', 'LeonGids', 'UK', 6);
insert into r6_team (team_name, coach, nationality, ranking) values ('Natus Vincere (NAVI)', 'Saves', 'Ukraine', 7);
insert into r6_team (team_name, coach, nationality, ranking) values ('Spacestation Gaming (SSG)', 'Lycan', 'USA', 8);
insert into r6_team (team_name, coach, nationality, ranking) values ('DarkZero Esports (DZ)', 'Panbazou', 'USA', 9);
insert into r6_team (team_name, coach, nationality, ranking) values ('Oxygen Esports', 'FoxA', 'USA', 10);
insert into r6_team (team_name, coach, nationality, ranking) values ('M80', 'Rb', 'USA', 11);
insert into r6_team (team_name, coach, nationality, ranking) values ('Soniqs', 'Supr', 'USA', 12);
insert into r6_team (team_name, coach, nationality, ranking) values ('w7m esports', 'Rdking', 'Brazil', 13);
insert into r6_team (team_name, coach, nationality, ranking) values ('Team Liquid', 'Paluh', 'Brazil', 14);
insert into r6_team (team_name, coach, nationality, ranking) values ('FaZe Clan', 'Cyber', 'Brazil', 15);
insert into r6_team (team_name, coach, nationality, ranking) values ('Los + oNe', 'Novys', 'Brazil', 16);
insert into r6_team (team_name, coach, nationality, ranking) values ('FURIA Esports', 'Miracle', 'Brazil', 17);
insert into r6_team (team_name, coach, nationality, ranking) values ('FURY', 'Derpeh', 'Australia', 18);
insert into r6_team (team_name, coach, nationality, ranking) values ('Elevate', 'HysteRiX', 'Southeast Asia', 19);
insert into r6_team (team_name, coach, nationality, ranking) values ('Dplus', 'EnvyTaylor', 'South Korea', 20);
insert into r6_team (team_name, coach, nationality, ranking) values ('SCARZ', 'Gatorada', 'Japan', 21);